# Generated by Django 3.0.5 on 2020-04-21 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('course_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50)),
                ('season', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Course_book',
            fields=[
                ('author', models.CharField(max_length=50)),
                ('book_title', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('material_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('link_to_download', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Course_lecturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('moderator_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('moderator_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('password_hash', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('group_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('professor_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('password_hash', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='course_lecturer',
            name='lecturer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Teacher'),
        ),
    ]
