# Generated by Django 3.0.6 on 2020-05-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200421_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_info',
            field=models.TextField(default='-'),
        ),
    ]
