# Generated by Django 3.0.5 on 2020-05-05 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_course_course_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_lecturer',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='course_lecturer',
            name='lecturer_id',
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Course_lecturer',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
